const assert=require('node:assert/strict');
const M=require('./menu-input.js');
const l=[{x:.5,y:.4,visibility:1}];
l[11]={x:400,y:400,visibility:1};l[12]={x:600,y:400,visibility:1};l[15]={x:700,y:300,visibility:1};l[16]={x:800,y:300,visibility:1};
const c=M.joinedCursor(l);
assert.ok(c,'joined hands create one menu cursor with no legs');
assert.equal(c.x,750,'cursor is exactly midway between two hand markers');
assert.equal(c.y,300,'cursor is exactly midway between two hand markers');
assert.ok(M.inRect(c,700,200,200,200));
const noHands=l.map(p=>p&&({...p}));noHands[15].visibility=.2;noHands[16].visibility=.2;
assert.equal(M.joinedCursor(noHands),null,'low-confidence hands cannot select');
const noShoulders=l.map(p=>p&&({...p}));noShoulders[11].visibility=.2;
assert.equal(M.joinedCursor(noShoulders),null,'shoulders gate cursor scale');
const apart=l.map(p=>p&&({...p}));apart[15].x=100;apart[16].x=900;
assert.equal(M.joinedCursor(apart),null,'separated hands hide menu cursor');
console.log('PASS: joined-hands midpoint menu cursor, confidence, distance, hit testing');
