const assert=require('node:assert/strict');
const E=require('./question-evaluator.js');
const values={A:4,B:3,C:7,D:2};
assert.equal(E.evaluate('A+B*C',values),25);
assert.equal(E.evaluate("A>B ? A+'/'+C : B+'/'+C",values),'4/7');
assert.equal(E.evaluate("(A+B)===(C)?'=':'≠'",values),'=');
assert.equal(E.evaluate('repeatAdd(A, B)',values),'4 + 4 + 4');
assert.equal(E.evaluate('Math.abs(A-B)',values),1);
assert.throws(()=>E.evaluate('window.alert(1)',values),/Unsupported/);
assert.throws(()=>E.evaluate('A.constructor',values),/Unsupported/);
console.log('PASS: restricted CSV evaluator supports math templates and rejects code execution');
